language: php
php:
  - '5.6'
  - '7.0'
service:
  - mysql
  - postgresl
before_install:
  - mysql -u root --default-character-set=utf8 < tests/Bitmap/resources/Chinook_MySql_AutoIncrementPKs.sql
  - psql postgres -f tests/Bitmap/resources/Chinook_PostgreSql.sql
install:
  - composer install