language: php
php:
  - '5.6'
  - '7.0'
service:
  - mysql
  - postgresl
before_install:
  - mysql -u root --default-character-set=utf8 < tests/Bitmap/resources/Chinook_MySql_AutoIncrementPKs.sql
  - psql -U postgres -c 'create database Chinook;'
  - psql -U postgres Chinook -f tests/Bitmap/resources/Chinook_PostgreSql.sql > /dev/null 2>&1
install:
  - composer install